//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mentorproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MentorRegistration
    {
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Passsword { get; set; }
        public Nullable<long> Mobile { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string country { get; set; }
    }
}
