//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mentorproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mentor_TakenSessionDetails
    {
        public int MentorId { get; set; }
        public int DomainId { get; set; }
        public int AttendeesCount { get; set; }
        public int SessionId { get; set; }
        public System.DateTime SessionDate { get; set; }
        public int SessionStart { get; set; }
        public int SessionEnd { get; set; }
        public double SessionAmount { get; set; }
    }
}
