//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mentorproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MentorProfile
    {
        public int MentorId { get; set; }
        public Nullable<int> DomainId { get; set; }
        public Nullable<int> IndustryExperience { get; set; }
        public Nullable<int> MentoringExperience { get; set; }
        public string Skills { get; set; }
        public Nullable<System.DateTime> AvailableFrom { get; set; }
        public Nullable<System.DateTime> AvailableTo { get; set; }
    }
}
